### ISSUE TITLE
`kime-xim` panics on start

### ISSUE THREAD

**Issue by scarf005** [Riey/kime#623]
### 개요
```
$ RUST_BACKTRACE=1 kime-xim --verbose
[ INFO] Found previous XIM_SERVER it will overrided
[ INFO] Start server win: 113246208
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/frontends/xim/src/handler.rs:46:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: kime_xim::handler::KimeHandler::new
   4: kime_xim::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

카카오톡 한글 입력이 되지 않아 #420 에서 나온 방법을 시도하자 `kime-xim`이 패닉을 일으켰습니다.

### 시스템 정보
```
$ kime --version
kime 3.0.1

`kime` 0.1.0

$ kime-xim --version
kime 3.0.1

`kime-xim` 0.3.0
```

```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-58-generic (64-bit)
Graphics Platform: X11
```

**Comment by Riey** [comment]
폰트가 미설치 된것 같네요

**Comment by scarf005** [comment]
혹시 어떤 폰트가 미설치 되었는지 알 수 있을까요?

**Comment by Riey** [comment]
3.0.2로 업그레이드 해보세요 패키지 의존성에 폰트가 추가됐습니다

**Comment by Riey** [comment]
폰트는 3.0.1 기준으론 d2coding 설치하시면 될겁니다

**Comment by scarf005** [comment]
`3.0.2`로 올린 후 잘 실행됩니다. 감사합니다!
```
$ kime-xim --version
kime 3.0.2

`kime-xim` 0.3.0

$ RUST_BACKTRACE=1 kime-xim --verbose
[ INFO] Found previous XIM_SERVER it will overrided
[ INFO] Start server win: 132120576
```

**Comment by scarf005** [comment]
#611 의 중복이었네요 표시 수정하겠습니다
